# fly.toml app configuration file generated for jtaf4 on 2025-06-09T15:26:22+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jtaf4'
primary_region = 'fra'

[build]

[[mounts]]
  source = 'tmp'
  destination = '/tmp'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '20s'
    method = 'GET'
    path = '/actuator/health'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
