name: Release

on:
    push:
        tags:
            - "*.*.*"

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            contents: 'read'
            id-token: 'write'

        steps:
            -   uses: actions/checkout@v4

            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    java-version: '21'
                    distribution: 'adopt'

            -   name: Cache local Maven repository
                uses: actions/cache@v4
                with:
                    path: ~/.m2/repository
                    key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                    restore-keys: |
                        ${{ runner.os }}-maven-

            -   name: Maven Build
                run: ./mvnw -B clean package -Pproduction

            -   name: Deploy to Jelastic
                uses: jelastic/jelastic-maven-plugin@v1
                with:
                    jelastic_url: https://app.hidora.com
                    jelastic_token: ${{ secrets.JELASTIC_TOKEN }}
                    environment: jtaf4
